version: "2.4"

services:
  demo-server:
    build:
      context: demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    volumes:
      - gradle-cache:/home/gradle/.gradle
    networks:
      - backend
      - frontend

  demo-front-end:
    build:
      context: front-end-demo
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    depends_on:
      - demo-server
    networks:
      - frontend

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  gradle-cache:


